services:
  knight-bite:
    container_name: knight-bite

    build: .

    image: kabshataiyub/knight-bite:v${BUILD_NUMBER}

    restart: always

    ports:
      - "9090:80"

    networks:
      - my-network

networks:
  my-network:
